grep ptm *.pdb >                    ptm.scores
grep plddt_mean *.pdb >             plddt_mean.scores
grep plddt_median *.pdb >           plddt_median.scores
grep plddt_std *.pdb >              plddt_std.scores
grep plddt_min *.pdb >              plddt_min.scores
grep plddt_max *.pdb >              plddt_max.scores
grep plddt_range *.pdb >            plddt_range.scores
grep pae_mean *.pdb >               pae_mean.scores
grep pae_median *.pdb >             pae_median.scores
grep pae_std *.pdb >                pae_std.scores
grep pae_min *.pdb >                pae_min.scores
grep pae_max *.pdb >                pae_max.scores
grep pae_range *.pdb >              pae_range.scores
grep pae_off_diag_mean *.pdb >      pae_off_diag_mean.scores
grep pae_off_diag_median *.pdb >    pae_off_diag_median.scores
grep pae_off_diag_std *.pdb >       pae_off_diag_std.scores
grep pae_off_diag_min *.pdb >       pae_off_diag_min.scores
grep pae_off_diag_max *.pdb >       pae_off_diag_max.scores
grep pae_off_diag_range *.pdb >     pae_off_diag_range.scores
grep pae_contacts_8A_num *.pdb >    pae_contacts_8A_num.scores
grep pae_contacts_8A_mean *.pdb >   pae_contacts_8A_mean.scores
grep pae_contacts_8A_median *.pdb > pae_contacts_8A_median.scores
grep pae_contacts_8A_std *.pdb >    pae_contacts_8A_std.scores
grep pae_contacts_8A_min *.pdb >    pae_contacts_8A_min.scores
grep pae_contacts_8A_max *.pdb >    pae_contacts_8A_max.scores
grep pae_contacts_8A_range *.pdb >  pae_contacts_8A_range.scores
grep pae_contacts_10A_num *.pdb >   pae_contacts_10A_num.scores
grep pae_contacts_10A_mean *.pdb >  pae_contacts_10A_mean.scores
grep pae_contacts_10A_median *.pdb >pae_contacts_10A_median.scores
grep pae_contacts_10A_std *.pdb >   pae_contacts_10A_std.scores
grep pae_contacts_10A_min *.pdb >   pae_contacts_10A_min.scores
grep pae_contacts_10A_max *.pdb >   pae_contacts_10A_max.scores
grep pae_contacts_10A_range *.pdb > pae_contacts_10A_range.scores
grep pae_contacts_12A_num *.pdb >   pae_contacts_12A_num.scores
grep pae_contacts_12A_mean *.pdb >  pae_contacts_12A_mean.scores
grep pae_contacts_12A_median *.pdb >pae_contacts_12A_median.scores
grep pae_contacts_12A_std *.pdb >   pae_contacts_12A_std.scores
grep pae_contacts_12A_min *.pdb >   pae_contacts_12A_min.scores
grep pae_contacts_12A_max *.pdb >   pae_contacts_12A_max.scores
grep pae_contacts_12A_range *.pdb > pae_contacts_12A_range.scores
